### ISSUE TITLE
Add as SwiftUI `.keyboardShortcut()` helper

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/KeyboardShortcuts#101]
https://github.com/sindresorhus/KeyboardShortcuts/pull/69

**Comment by DeLoeribas** [comment]
Now I have updated to this version I get a `Cannot find 'LabeledContent' in scope` error (line 63 in Recorder.swift). I am using KeyboardShortcuts in a non SwiftUI application.

**Comment by mbenoukaiss** [comment]
For anyone interested I needed it so I implemented it manually thanks to this answer on StackOverflow https://stackoverflow.com/a/35138823. Maybe there's a cleaner way to implement `toEventModifiers`.

```swift
struct SomeView: View {

    var body: some View {
        let shortcut = KeyboardShortcuts.Name("...").shortcut!
        
        return Button("Shortcut") {
            print("clicked")
        }.keyboardShortcut(
            toKeyEquivalent(shortcut.carbonKeyCode)!,
            modifiers: toEventModifiers(shortcut.modifiers)
        )
    }

    func toKeyEquivalent(_ carbonKeyCode: Int) -> KeyEquivalent? {
        let maxNameLength = 4
        var nameBuffer = [UniChar](repeating: 0, count : maxNameLength)
        var nameLength = 0
        
        let modifierKeys = UInt32(alphaLock >> 8) & 0xFF // Caps Lock
        var deadKeys: UInt32 = 0
        let keyboardType = UInt32(LMGetKbdType())
        
        let source = TISCopyCurrentKeyboardLayoutInputSource().takeRetainedValue()
        guard let ptr = TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData) else {
            NSLog("Could not get keyboard layout data")
            return nil
        }
        let layoutData = Unmanaged<CFData>.fromOpaque(ptr).takeUnretainedValue() as Data
        let osStatus = layoutData.withUnsafeBytes {
            UCKeyTranslate($0.bindMemory(to: UCKeyboardLayout.self).baseAddress, UInt16(carbonKeyCode), UInt16(kUCKeyActionDown),
                           modifierKeys, keyboardType, UInt32(kUCKeyTranslateNoDeadKeysMask),
                           &deadKeys, maxNameLength, &nameLength, &nameBuffer)
        }
        guard osStatus == noErr else {
            NSLog("Code: 0x%04X  Status: %+i", carbonKeyCode, osStatus);
            return nil
        }
        
        return KeyEquivalent(Character(String(utf16CodeUnits: nameBuffer, count: nameLength)))
    }
    
    func toEventModifiers(_ nsModifiers: NSEvent.ModifierFlags) -> SwiftUI.EventModifiers {
        var modifiers: SwiftUI.EventModifiers = []
        
        if nsModifiers.contains(NSEvent.ModifierFlags.command) {
            modifiers.update(with: EventModifiers.command)
        }
        
        if nsModifiers.contains(NSEvent.ModifierFlags.control) {
            modifiers.update(with: EventModifiers.control)
        }
        
        if nsModifiers.contains(NSEvent.ModifierFlags.option) {
            modifiers.update(with: EventModifiers.option)
        }
        
        if nsModifiers.contains(NSEvent.ModifierFlags.shift) {
            modifiers.update(with: EventModifiers.shift)
        }
        
        if nsModifiers.contains(NSEvent.ModifierFlags.capsLock) {
            modifiers.update(with: EventModifiers.capsLock)
        }
        
        if nsModifiers.contains(NSEvent.ModifierFlags.numericPad) {
            modifiers.update(with: EventModifiers.numericPad)
        }
        
        return modifiers
    }
}
```

**Comment by augustwester** [comment]
Thanks, @mbenoukaiss! 🙏 How would you extend this so the menu bar item is updated dynamically? You currently have to restart the app for changes to take effect.

**Comment by othyn** [comment]
This is a necessity when using this package with `MenuBarExtra` Button components.

**Comment by castdrian** [comment]
I agree, this is exactly where I'm at as well

**Comment by scornflake** [comment]
A little late to the party, but I've just raised a PR that solves this (same idea, different SwiftUI wrapper, which auto updates based on changes to the Shortcut state)

see: https://github.com/sindresorhus/KeyboardShortcuts/pull/181

**Comment by aueangpanit** [comment]
For anyone who needs it quickly! I've forked this project because I wanted this change this weekend 🙂 -> https://github.com/aueangpanit/KeyboardShortcuts

Example usage:
`
Button(action: captureTextViewModel.captureText, label: { Text("Capture Text") }).keyboardShortcut(for: KeyboardShortcuts.Name("captureText"))
`

---

In case it's helpful, all of the changes for this feature in this file: https://github.com/aueangpanit/KeyboardShortcuts/blob/main/Sources/KeyboardShortcuts/View%2B%2B.swift

Hopefully, we have it in the main project soon! ❤️

**Comment by sarensw** [comment]
Hi @sindresorhus , thank you so much for providing a fix here. Just want to double check. This is how I use the MenuBarExtra right now. But, when I change the shortcut for that it is not reflected in the Button label. It works as expected, but the label still shows the previous shortcut until I restart the app. Is there anything that I have to do in addition to make this work?

```
MenuBarExtra("...", image: "...") {
    Button("Show") {
        ...
    }
    .globalKeyboardShortcut(.showPanel)
}
```

**Comment by rampatra** [comment]
I just tested this on my app and the key shortcut changes are reflected instantly. No need for restart. My code looks the same as yours.

Btw, this feature made this library perfect. Thanks, @sindresorhus.

**Comment by sarensw** [comment]
@rampatra thanks for checking. Just to double check: On which macOS are you?

**Comment by sarensw** [comment]
I have just checked on my macOS 13 and macOS 15 virtual machines. No issue there. My dev env is still on macOS 14. I guess this is some set-up related issue on my side.
