### ISSUE TITLE
LabeledContent error

### ISSUE THREAD

**Issue by DeLoeribas** [sindresorhus/KeyboardShortcuts#102]
Now I have updated to this version, I get a `Cannot find 'LabeledContent' in scope` error (line 63 in Recorder.swift). I am using KeyboardShortcuts in a non SwiftUI application.

**Comment by sindresorhus** [comment]
You need Xcode 14 for this release.

**Comment by DeLoeribas** [comment]
I am running on Xcode Version 14.0.1 (14A400)

**Comment by sindresorhus** [comment]
Sorry, I meant to write Xcode 14.1.
