### ISSUE TITLE
Recorder onChange callback

### ISSUE THREAD

**Issue by gpoitch** [sindresorhus/KeyboardShortcuts#11]
Looking for an api to be notified when a recorder view successfully changes/removes its shortcut.  Something like:

```swift
KeyboardShortcuts.RecorderCocoa(for: .doSomething, onChange: { (shortcut: KeyboardShortcuts.Shortcut) in
 // do something with new shortcut key
})
```

I have my own preferences storage solution set up in an existing app and I want to update it when the recorder changes.  I suppose I'd like to disable the build-in UserDefaults storage as well, but not that's not a big deal.

**Comment by sindresorhus** [comment]
Makes sense. The `shortcut` given to the closure would need to be an optional though, so when the shortcut is cleared, it would be `nil`.

**Comment by sindresorhus** [comment]
I’m busy for the next 2 weeks, but I will pick up this after, unless someone wants to do a PR before then.

**Comment by gpoitch** [comment]
PR: #12
