### ISSUE TITLE
Is the library only supports global shortcuts or local too?

### ISSUE THREAD

**Issue by pradeepb28** [sindresorhus/KeyboardShortcuts#112]
Is it possible to register keyboard shortcuts for local events? Thank you!

**Comment by sindresorhus** [comment]
Global only. With local shortcuts, you can just use `View#keyboardShortcut()` in SwiftUI.

**Comment by Maschina** [comment]
That may be a potential implementation if you don't want to have an extra button for it: https://stackoverflow.com/a/74783234/873072
