### ISSUE TITLE
Is default keyboard shortcut has any bug?

### ISSUE THREAD

**Issue by pradeepb28** [sindresorhus/KeyboardShortcuts#113]
I have following keyboard shortcut that assigned a default value - Option + Tab but the observer doesn't gets called

```
extension KeyboardShortcuts.Name { 
    static let switch = Self("switch", default: .init(.tab, modifiers: [.option])) 
}
```

In App delegate I have an observer

```
func applicationDidFinishLaunching(_ aNotification: Notification) {
     KeyboardShortcuts.onKeyUp(for: .switch) {
            print("Option+Tab was pressed")
        }
}
```

by the way if the Option + Tab when set in Recorder field, it works fine but when it was assigned as default then no.

My question is
- Is the above code enough to register a default keyboard shortcut? (I couldn't find much in the documentation in Readme file)

Any help is appreciated. Thank you.

**Comment by sindresorhus** [comment]
The `default` parameter means it will fill out the keyboard shortcut into the recorder initially. But if the recorder has already had a value, it will not fill out. I think the parameter is misnamed. It should have been named `initial` as that's what it is — It's the initial value before any value has been set by the user.

**Comment by pradeepb28** [comment]
In my case, I made sure that recorder doesn't have a value at all.
