### ISSUE TITLE
keyboardshortcuts shows wrong key on the NSMenu

### ISSUE THREAD

**Issue by pradeepb28** [sindresorhus/KeyboardShortcuts#116]
I have a shortcut that I had set with option+tab to open an app, it works accordingly but on the UI it shows command + option symbols.

**_Settings_**
![CleanShot 2022-12-17 at 12 11 42](https://user-images.githubusercontent.com/6823101/208229340-7148644a-9077-484f-906e-72f48fa853ff.png)

**_NSMenu_**
![CleanShot 2022-12-17 at 12 11 14](https://user-images.githubusercontent.com/6823101/208229342-c53754f3-c9ea-4a32-8439-cff08f6d1213.png)

I used KeyboardShortcuts.getShorcut(...).description  to assign the value on the UI

When I simply use print statement, it shows correct symbols.

Conclusion: On the UI it shows different symbol but functionally it works as expected as option+tab commands

**Comment by sindresorhus** [comment]
That is the wrong way to do it. See: https://github.com/sindresorhus/KeyboardShortcuts/blob/0dcedd56994d871f243f3d9c76590bfd9f8aba69/Sources/KeyboardShortcuts/NSMenuItem%2B%2B.swift#L14-L41
