### ISSUE TITLE
Bug in macOS 13 but with minimum development target set to macOS 12

### ISSUE THREAD

**Issue by Fiser12** [sindresorhus/KeyboardShortcuts#123]
I have an issue, my device is macOS 13 but my minimum development target is macOS 12, that generates this issue

<img width="1045" alt="imagen" src="https://user-images.githubusercontent.com/7186913/220619905-74683943-e63c-4e9d-aeff-3dba642cf841.png">

Thanks! your repo is awesome

**Comment by sindresorhus** [comment]
You need the latest Xcode version.
