### ISSUE TITLE
Allow to use in XIB

### ISSUE THREAD

**Issue by p0deje** [sindresorhus/KeyboardShortcuts#14]
Hello, thank you for the great package!

I'm trying to figure out how to use recorded in Interface Builder? I'd normally add custom view and set its class to `KeyboardShortcuts.RecorderCocoa` but it doesn't work. I couldn't find any documentation about this too.

Is it possible to use `KeyboardShortcuts.RecorderCocoa` from XIB files?

**Comment by sindresorhus** [comment]
That was not implemented as I had problems in the past where Interface Builder wouldn't display custom views from a package, and also, it's not something I needed personally. Happy to accept a PR to add it, but it's not something I plan to work on.

It's probably the easiest to just add a custom view in Interface Builder, get an outlet reference, and then programmatically add `RecorderCocoa` as a subview. I can document that in the readme.

**Comment by p0deje** [comment]
Fair enough - the package is great without it as well. 

I managed to get it working but I don't know Cocoa programming well enough and it took me some time to figure it out. I was migrating from https://github.com/Clipy/KeyHolder which has this feature and it's nice to see what you get in XIB files (though there are additional workarounds I had to do make it work https://github.com/Clipy/KeyHolder/issues/6).

I'm not experienced enough to send a PR to add this. Feel free to close the issue if you want.

**Comment by L1cardo** [comment]
This will be really nice if we can just drag a `KeyboardShortcuts.RecorderCocoa` to storyboard.
I don't know if this can be done now, but it seems that Swift5.3 allows to attach  xib resources to Swift Packages.
Maybe I can do something on this, but no promises.

**Comment by sindresorhus** [comment]
I have decided to pass on this. SwiftUI is quickly maturing and I personally don't have any XIB/Storyboard usage left to warrant maintaining this.
