### ISSUE TITLE
Add ability to override a key name (Change _ to "Space")

### ISSUE THREAD

**Issue by stammy** [sindresorhus/KeyboardShortcuts#141]
It would be great to have a way to be able to change the space identifier used (shown below) to the more descriptive string "Space". We've seen a lot of user feedback that the identifier is confusing and just spelling it out would be more recognizable. 

Maybe Space could be moved to Localizable strings like this? https://github.com/stammy/KeyboardShortcuts/commit/9f52ccbddee4f257e661719317012751e28c9cbb

<img width="331" alt="CleanShot 2023-08-15 at 12 18 55" src="https://github.com/sindresorhus/KeyboardShortcuts/assets/30445/90657ee7-a757-4d5f-a3e0-56f591f3a047">

<img width="138" alt="CleanShot 2023-08-15 at 12 18 26" src="https://github.com/sindresorhus/KeyboardShortcuts/assets/30445/b58d5f78-9429-41c8-9e7f-84fa7c9f3517">

**Comment by stammy** [comment]
Thanks @sindresorhus!

**Comment by sindresorhus** [comment]
I changed it. macOS uses `Space`: https://github.com/sindresorhus/KeyboardShortcuts/releases/tag/1.14.0

<img width="87" alt="Screenshot 2023-08-15 at 21 00 02" src="https://github.com/sindresorhus/KeyboardShortcuts/assets/170270/81041390-50f0-4fdd-acb1-5cce244f7f23">
