### ISSUE TITLE
the KeyboardShortcut Recorder still gets the focus by default in certain cases

### ISSUE THREAD

**Issue by godbout** [sindresorhus/KeyboardShortcuts#145]
this doesn't happen when you first show your Settings dialog, but it happens at a later stage, if you start fingering the Recorder. this can be easily seen in the latest version of Plash. that will cause the issue reported in #144. see below:

https://github.com/sindresorhus/KeyboardShortcuts/assets/121373/71ef4e95-64af-4bf6-b489-b5af35fc6af9

**Comment by godbout** [comment]
🙏️

**Comment by godbout** [comment]
@sindresorhus still getting the issue for that one. (the closing the Settings window issue is fixed.) anything i can do to help troubleshoot?

**Comment by sindresorhus** [comment]
I'm unable to reproduce this with the latest version together with Plash. Are you able to reproduce in Plash?

If it's only reproducible in your app, can you try replacing https://github.com/sindresorhus/KeyboardShortcuts/commit/b878f8132be59576fc87e39405b1914eff9f55d3#diff-41fc3abd80062ae3c8634038c89a3495bcd1d2455c1ff5cd5aa022f3409c6d8dR146-R149 with:

```swift
if #available(macOS 13, *) {
	Task {
		try? await Task.sleep(for: .seconds(0.5))
		canBecomeKey = true
	}
}
```

**Comment by godbout** [comment]
will do in a couple of hours. will try the latest version of Plash, my apps, the replacement you propose, and may create a bare repo showing the issue if necessary. thanks.

**Comment by godbout** [comment]
1. i'm unable to reproduce on Plash either, it seems
2. i've replace the code in `RecorderCocoa` by the snippet above, same thing, doesn't work in my apps
3. if i just make `canBecomeKey = false` then everything works fine 😂️ (but haven't had dug yet about side effects

so i guess it's something in my apps. will dig. and will try to make a project from scratch and see.
also i'm on macOS 14, latest public beta if that matters. will work on latest macOS 13 tomorrow. also Plash is all good under macOS 14 so probably not the issue.

**Comment by godbout** [comment]
dumping what i'm finding: if i show my Settings window from launching the app again, or through pressing `command ,` on my input-à-la-Alfred, then the KeyboardShortcut doesn't take focus. but if i do through the status menu item it does. they all call the same static func of a class. so not sure what's going on 😂️

**Comment by godbout** [comment]
i made a project from scratch with bare minimum code and the issue doesn't show up. so it has to be on my side. i'll try to figure out why, and i'll update here for reference. but as far as you're concerned, all is good on your side. thanks again Sindre!

**Comment by godbout** [comment]
found it. it's coming from that func in my AppDelegates:

```swift
func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
    // that means this is called on Settings, not on The Inspector LOL
    if sender.keyWindow == nil {
        NSApp.hide(self)
    }
        
    return false
}
```

for whatever reason this causes the issue with the KeyboardShortcuts Recorder. will see what i can do now from my side.

**Comment by godbout** [comment]
so if anyone is struggling with the same issue, here's a summary of what makes it happen, and how i finally solved it:

1. the issue happens when 1) you hide your own app (i do this when the last window gets closed so that macOS goes back to focusing on the previously focused app) 2) at a later stage you open your app's Settings from the menu bar (it doesn't happen through any other mean even if the code is the same)

in that case the KeyboardShortcut Recorder grabs the focus, which kinda locks the user:

https://github.com/user-attachments/assets/41cb4914-02ad-4946-9852-e7fd1a243667

2. in the past i had forked the repo to prevent the Recorder to become key, but that would create two issues. first i wouldn't be able to programmatically focus the Recorder which i wanted to do in some cases (see video below). second users couldn't focus the Recorder with `tab`. so ultimately still not satisfying (but better than locking the user in).

https://github.com/user-attachments/assets/021c8692-d15d-402f-a493-c3f712ac9ea0

3. to fix all of the issues, i've ended up `disabling` the Recorder by default, and enabling it when the Form loads lol. the enabling being async i guess SwiftUI starts 1) disabling the Recorder 2) trying to focus on the Recorder but it's disable so cannot. then the async enabling finally allows the user to `tab` to the Recorder, or my app to programmatically focus on it, all while avoiding the initial auto focusing.

https://github.com/user-attachments/assets/bc3eced3-b76e-4760-845d-6fb816e3833e

for info i had tried to set the @FocusState to false but SwiftUI being so shit and slow the Recorder would blink when loading the Form:

https://github.com/user-attachments/assets/d16efb9d-86b8-4827-b4a4-17c0747bc257

**Comment by godbout** [comment]
the code itself is pretty basic, issue was figuring out when the bug was happening, and how to avoid it in all cases:

```swift
struct GeneralPane: View {
    
    @State private var recorderIsDisabled: Bool = true
    
    var body: some View {
        Form {
            HStack {
                VStack(alignment: .leading) {
                    SuperGeneral()
                        .padding(.top, 0.5)
                        .padding(.bottom, 10)
                    Divider()
                        .opacity(0)
                    HStack {
                        Text("Start Wooshing with:")
                        KeyboardShortcuts.Recorder(for: .toggleWith)
                            .disabled(recorderIsDisabled)
                            
                    }
                }
                Spacer()
            }
        }
        .onAppear {
            DispatchQueue.main.async {
                recorderIsDisabled = false
            }
        }
        .onDisappear {
            DispatchQueue.main.async {
                recorderIsDisabled = true
            }
        }
        .frame(width: 388)
    }
    
}
```
