### ISSUE TITLE
Can I still use the spacebar for spacing after setting it as a shortcut key?

### ISSUE THREAD

**Issue by asaxing** [sindresorhus/KeyboardShortcuts#146]
After setting the spacebar as a shortcut, I can no longer input spaces in TextEditor. 
Does anyone know how to fix this issue? thanks

**Comment by sindresorhus** [comment]
You could disable the shortcut when a text editor is focused. I'm not aware of a better way to handle this. That's why it's generally smart to combine it with a modifier.
