### ISSUE TITLE
I hope show system-wide keyboard shortcut name

### ISSUE THREAD

**Issue by unknown-codemonkey** [sindresorhus/KeyboardShortcuts#155]
It would be nice to display the name of the system shortcut, so that you can know which shortcut conflicts with the system.

<img width="416" alt="image" src="https://github.com/sindresorhus/KeyboardShortcuts/assets/140239992/ce84b79b-438c-46b5-a739-09fd31205f41">

**Comment by sindresorhus** [comment]
macOS does not provide this information.
