### ISSUE TITLE
Complying with Encryption Export Regulations

### ISSUE THREAD

**Issue by chrs1885** [sindresorhus/KeyboardShortcuts#157]
When submitting an app to the App Store you need to provide information about [types of encryption](https://developer.apple.com/documentation/security/complying_with_encryption_export_regulations) that were used within the app or within any of the libraries it links against.

Does KeyboardShortcut use encryption or forms of encryption that are not built into the operating system?

**Comment by sindresorhus** [comment]
It does not.
