### ISSUE TITLE
Slovak translation

### ISSUE THREAD

**Issue by Svec-Tomas** [sindresorhus/KeyboardShortcuts#159]
Hey! I am sorry, I am not really familiar with GitHub and Pull requests. But I have localised KeyboardShortcuts to my native language - Slovak as it is used in MonitorControl, which I have localised as well. Please find it attached to this post.

Thanks!
[Keyboard Shortcuts Slovak.zip](https://github.com/sindresorhus/KeyboardShortcuts/files/13757478/Keyboard.Shortcuts.Slovak.zip)

**Comment by Svec-Tomas** [comment]
Hi Sindre and a Happy New Year! Is this still maintained, please? I see Polish Pull request for a long time now also not finished. Thanks.

**Comment by sindresorhus** [comment]
Thanks :)

https://github.com/sindresorhus/KeyboardShortcuts/releases/tag/1.17.0
