### ISSUE TITLE
Manually set a keyboard shortcut for a name

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/KeyboardShortcuts#16]
This can be useful for migrating over to this package from some other solution.

Inside some one-time migration method:

```swift
let shortcut = KeyboardShortcuts.Shortcut(carbonKeycode: someHotkey, carbonModifiers: someModifiers)

KeyboardShortcuts.Name.foo.shortcut = shortcut
```

Alternatively:

```swift
let shortcut = KeyboardShortcuts.Shortcut(carbonKeycode: someHotkey, carbonModifiers: someModifiers)

KeyboardShortcuts.Name.set(shortcut, for: .foo)
```

That way, the user doesn't need to know the implementation details on how it's stored. Like here: https://github.com/p0deje/Maccy/commit/1001035d611cb411df702a941f5eb40626fc5ea7#diff-2589021fe69dedfc5619fc6a19136f23R117-R126

@p0deje Any thoughts?

**Comment by p0deje** [comment]
This would be great indeed as I had to read through the sources to figure out the storage mechanism. Another possible solution would be to allow to customize storage strategy that can be implemented to provide backwards compatiblity during the app migration. The silly implementation I used to have was to just write `"command+shift+C"` string to my own UserDefaults, then parse it and construct a shortcut.

**Comment by sindresorhus** [comment]
> Another possible solution would be to allow to customize storage strategy that can be implemented to provide backwards compatiblity during the app migration.

Agreed. I could use your thoughts in https://github.com/sindresorhus/KeyboardShortcuts/issues/18.
