### ISSUE TITLE
Dynamic keyboard shortcuts?

### ISSUE THREAD

**Issue by pradeepb28** [sindresorhus/KeyboardShortcuts#160]
I have a dynamic size list and i want to assign keyboard shortcut for each item. Since the size is unknown, is it possible to set Keyboard shortcuts dynamically based off the list and also delete it dynamically? 

Thank you!

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/KeyboardShortcuts#dynamic-keyboard-shortcuts
