### ISSUE TITLE
"Space" is not localized

### ISSUE THREAD

**Issue by NachoSoto** [sindresorhus/KeyboardShortcuts#172]
See #141 and 43bedc929042742384e5a87b576c17de5394bd7e.

This was changed to "space", but not localized:
<img width="151" alt="Screenshot 2024-05-22 at 13 56 20" src="https://github.com/sindresorhus/KeyboardShortcuts/assets/685609/5e48b4a4-8064-4f15-9328-0dacec194fa7">

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/KeyboardShortcuts/releases/tag/2.0.1

**Comment by NachoSoto** [comment]
Awesome thanks!
