### ISSUE TITLE
NSViewBridgeErrorCanceled inside NSHostingView

### ISSUE THREAD

**Issue by tcurdt** [sindresorhus/KeyboardShortcuts#185]
I am seeing this

```
ViewBridge to RemoteViewService Terminated: Error Domain=com.apple.ViewBridge Code=18 "(null)" UserInfo={com.apple.ViewBridge.error.hint=this process disconnected remote view controller -- benign unless unexpected, com.apple.ViewBridge.error.description=NSViewBridgeErrorCanceled}
```

when using `KeyboardShortcuts.Recorder(for: .foo)` inside a `NSHostingView`.

Funnily enough it still seems to work correctly.

Has anyone seen that before and has any pointers what might be wrong?
General search suggests this could be a general problem in Sequoia?

https://forums.developer.apple.com/forums/thread/764235

**Comment by sindresorhus** [comment]
Most logging like this is unrelated to your app and packages.
