### ISSUE TITLE
CLIENT ERROR: TUINSRemoteViewController does not override -viewServiceDidTerminateWithError: and thus cannot react to catastrophic errors beyond logging them

### ISSUE THREAD

**Issue by I7T5** [sindresorhus/KeyboardShortcuts#188]
Xcode 16
MacBook Pro 2023 (M2 Pro)
macOS 14.6.1
Full Disk Access, Screen and Audio recording, and Input Monitor permissions granted

---

Hi I'm trying to incorporate keyboard shortcuts with my app. I want a global keyboard shortcut for taking a screenshot then doing [LaTex-OCR](https://github.com/lukas-blecher/LaTeX-OCR?tab=readme-ov-file) on it. The app does not give any bugs except every time I remove the keyboard shortcut it gives me the above / following error twice: 

```
CLIENT ERROR: TUINSRemoteViewController does not override -viewServiceDidTerminateWithError: and thus cannot react to catastrophic errors beyond logging them
```

and one instance of the following fault: 
```
FAULT: <NSRemoteView: 0x107d11f80 com.apple.TextInputUI.xpc.CursorUIViewService TUICursorUIViewService> determined it was necessary to configure <TUINSWindow: 0x107d0d2a0> to support remote view vibrancy
```

**Comment by sindresorhus** [comment]
That is logging from macOS and unrelated to this package.
