### ISSUE TITLE
Add ability to reset a shortcut

### ISSUE THREAD

**Issue by pavanpodila** [sindresorhus/KeyboardShortcuts#19]
This is a very useful package and the SwiftUI bindings make it a breeze to use. Please also add the ability to reset the shortcuts. I've tried resetting in the UserDefaults.standard directly but it didn't seem to have any effect.

I see that the code already has this ability, just that it needs to be exposed as a public API, say `KeyboardShortcuts.reset(name: Name)`

**Comment by sindresorhus** [comment]
Sure. Would you be able to elaborate what you need it for? That could be useful to include in the docs for it. Users don't always realize why they would want something.

**Comment by pavanpodila** [comment]
My app [QuickLens](https://quicklens.app) allows users to setup shortcuts for launching various tools. They also have an option to reset the app to all of its factory settings, including the global shortcuts. This is where I would be relying on the **reset** feature of `KeyboardShortcuts`. HTH.

**Comment by L1cardo** [comment]
I want a reset too

**Comment by gpoitch** [comment]
Just hit this too trying to implement "Restore Defaults" functionality.

Perhaps a more general `update` function could be added for programmatic changes.  Updating to `nil` would be "reset".

```swift
KeyboardShortcuts.Shortcut(name: .toggleUnicornMode)?.update(Shortcut(.a, modifiers: [.command])) // update
KeyboardShortcuts.Shortcut(name: .toggleUnicornMode)?.update(nil) // reset
```

**Comment by L1cardo** [comment]
![image](https://user-images.githubusercontent.com/33802186/88945686-df4ada80-d2c0-11ea-9a97-641c60c7a236.png)
Does this mean if I reset the UserDefault, I can reset the shorcut?

**Comment by sindresorhus** [comment]
> I don't think there is a listener for the changes happening on defaults.

Correct. That was not added yet: https://github.com/sindresorhus/KeyboardShortcuts/blob/61841e4dd562aeeb2206fe90f1e0734e5e2f809c/Sources/KeyboardShortcuts/KeyboardShortcuts.swift#L178-L181

Mostly because it's a bit of a chore to implement dynamic observation of specific keys in UserDefaults.
