### ISSUE TITLE
why trigger two times registering global event this way?

### ISSUE THREAD

**Issue by videni** [sindresorhus/KeyboardShortcuts#190]
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/f3706533-e920-4c90-bd0d-e3f189dffb5c">

as you can see the log

<img width="370" alt="image" src="https://github.com/user-attachments/assets/bcb8d115-c2f1-4538-9df8-e40c48aad3a7">

Once the ContentView disappears the global keybinding will not work. How to make sure the keybinding always works even the content view disappears?

**Comment by sindresorhus** [comment]
`ContentView` is deallocated when the window is not shown. The same applies to any modifiers. So this is not about this package.

As for a workaround, you could do something like this: https://gist.github.com/sindresorhus/90991161d21ae5a2c321d60724265bf1

**Comment by videni** [comment]
@sindresorhus  thanks, your workaround works.

**Comment by videni** [comment]
It seems the global variable is not released after the app quits.
```
@MainActor
private var globalTasks = [KeyboardShortcuts.Name: Task<Void, Never>]()
```
because I changed the key binding from `cmd + opt + k` to `space + opt`, then rebuilt the app, but the keybind is still the old one.
