### ISSUE TITLE
Disable all shortcuts and then re-enable them

### ISSUE THREAD

**Issue by pavanpodila** [sindresorhus/KeyboardShortcuts#20]
There should be a way to disable all shortcuts and then re-enable them. This is useful on a Preferences screen where you are registering a bunch of shortcuts. While you are entering new shortcuts, you should not be able to invoke the global shortcuts, especially when the control has focus. 

Currently there is no way to disable global hotkey monitoring.

**Comment by sindresorhus** [comment]
Hmm, shouldn't it just disable all shortcuts while a shortcut input is active? Wouldn't that be enough?

**Comment by pavanpodila** [comment]
I could do that, but will require looping through all the shortcuts individually to disable. I think a top level disable would be useful and convenient.

**Comment by sindresorhus** [comment]
Did you misunderstand my comment? I'm saying I think it's the responsibility of the input control to disable all shortcuts while the input control is active.

**Comment by pavanpodila** [comment]
Ok..I am doing that already. Just thought a single API to disable all would be handy.

**Comment by sindresorhus** [comment]
I still feel like we're talking past each other. I'm saying that I think **KeyboardShortcuts** should just handle this. No need for you to do anything. No need for an API.

**Comment by pavanpodila** [comment]
That would be ideal. And now I think we are on the same page ;-)
