### ISSUE TITLE
Action is called for many times

### ISSUE THREAD

**Issue by L1cardo** [sindresorhus/KeyboardShortcuts#21]
Keyboard shortcut action is called for many times, and fixed when relaunch the app. After I change the shortcut to another, it appears again, and disappears when relaunch the app.
The project is a Cocoa project.
Don't know if this is a Big Sur bug or anything else.
This problem never appeared on my another SwiftUI project. Maybe this is only a Cocoa problem?

![2020-07-27 13-50-00 2020-07-27 13_56_22](https://user-images.githubusercontent.com/33802186/88508332-1eeb9b00-d011-11ea-9eec-ced7f99641ad.gif)

**Comment by sindresorhus** [comment]
I cannot reproduce this with the example project in this repo. I would recommend trying to debug this a little bit more. First, ensure that the handler `onKeyDown` is called multiple times and that it's not your own code somewhere that is incorrect.
