### ISSUE TITLE
Allow dynamic keyboard shortcut names

### ISSUE THREAD

**Issue by frogg** [sindresorhus/KeyboardShortcuts#22]
My app has a use-case for adding shortcuts for user-defined actions.
Hence, I cannot register statically typed Keyboard Shortcuts names.

It would be great if the framework would allow for dynamic shortcut names.

Or is this already possible? I couldn't figure it out so far, sorry! Or is there an important reason why this has to be static?

Thanks for your help!

**Comment by sindresorhus** [comment]
We're only storing the shortcut names in `extension KeyboardShortcuts.Name` for convenience, to get dot-syntax access to the names at call-site. You can create `KeyboardShortcuts.Name`'s dynamically at any point and store them yourself.

**Comment by frogg** [comment]
That‘s great to know, thanks! Then this shouldn‘t be an issue at all.
