### ISSUE TITLE
Add `.resetAll()` method

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/KeyboardShortcuts#23]
Which would reset all the shortcuts in `extension KeyboardShortcuts.Name`.

This cannot be done until Swift supports [static key paths](https://forums.swift.org/t/key-path-cannot-refer-to-static-member/28055/2). We could potentially do something with `Mirror` today, but it's not important enough to do such a hacky workaround.

**Comment by Yang-Xijie** [comment]
Feature needed!

**Comment by Yang-Xijie** [comment]
Feature needed!

I set plenty of Shortcuts using their name. But some times these names gone, and I cannot find a way to reset them.

In the current documentation, I find two methods: `reset(names: ..)` which must use the shortcut name to reset and `removeAllHandlers()` which just remove handlers except for the shortcuts in UserDefault...

**Comment by sindresorhus** [comment]
The current workaround is to follow [this](https://github.com/sindresorhus/KeyboardShortcuts#get-all-keyboard-shortcuts) to get all the `Name`'s and pass them to `.reset(names: …)`.

**Comment by sindresorhus** [comment]
Added in https://github.com/sindresorhus/KeyboardShortcuts/releases/tag/2.2.0 with the caveat that it does not respect `.defaultShortcut`.
