### ISSUE TITLE
Mac Catalyst usage?

### ISSUE THREAD

**Issue by frogg** [sindresorhus/KeyboardShortcuts#29]
Thanks for this great framework, very useful!
I wanted to know if it is possible to use this framework on Mac Catalyst as well?

**Comment by sindresorhus** [comment]
This is not possible as the APIs used here are not available for Catalyst.

However, it's possible to use AppKit-only APIs from Catalyst:

- https://www.highcaffeinecontent.com/blog/20190607-Beyond-the-Checkbox-with-Catalyst-and-AppKit
- https://github.com/mhdhejazi/Catalyst-AppKit
