### ISSUE TITLE
Localizations

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/KeyboardShortcuts#3]
Would be nice to ship with localizations:
- The recorder button has a couple of words.
- The alert when the keyboard shortcut is taken by the system or by the app's main menu.

However, since we support Swift Package Manager, we cannot do this until Swift 5.3, which [supports resources](https://github.com/apple/swift-evolution/blob/master/proposals/0271-package-manager-resources.md).

**Comment by L1cardo** [comment]
This would be nice! So I just have to wait for Swift5.3 and then try to localize into Simplified Chinese

**Comment by sindresorhus** [comment]
This can now be done: https://developer.apple.com/documentation/swift_packages/bundling_resources_with_a_swift_package

While Xcode 12 is still beta and it won't work yet, there's no harm in adding the required files. They will just be noop in Xcode 11.
