### ISSUE TITLE
Keyboard shortcuts persist across app. 

### ISSUE THREAD

**Issue by kandelvijaya** [sindresorhus/KeyboardShortcuts#40]
Thanks for the project. I enjoyed the UI to allow user select Keyboard shortcuts. 

However this is what i found:

I set Cmd+f to TextField.becomeFirstResponder so that user can search within the app. Works great. 

I went to Xcode minizing the app but Cmd+f is taken. I felt weird and realized this is caused due to this new library i used.

**Comment by kandelvijaya** [comment]
Im using this code to do the trick for now:

```swift
.onChange(of: scenePhase, perform: { scene in
                    // Disable & Enable Find shortcut.
                    if scene == .active {
                        KeyboardShortcuts.enable(.focusFind)
                    }
                    if scene == .inactive {
                        KeyboardShortcuts.disable(.focusFind)
                    }
                })
```

**Comment by sindresorhus** [comment]
From the repo description:

> Add user-customizable **global** keyboard shortcuts to your macOS app in minutes

Emphasis on "global". For SwiftUI, you can just use `.keyboardShortcut()`, or when that doesn't work: https://developer.apple.com/documentation/appkit/nsevent/1534971-addlocalmonitorforevents
