### ISSUE TITLE
Can't record shortcuts when empty

### ISSUE THREAD

**Issue by adur1990** [sindresorhus/KeyboardShortcuts#41]
## Describe the bug
When the current shortcut is cleared and the the box is left empty, it is not possible to record a new shortcut anymore.

## To Reproduce
- Delete existing shortcut
- Click outside to deselect recorder field
- Try to click recorder field again

## Expected behavior
- A new shortcut should be recordable

## Desktop (please complete the following information)
 - macOS version: Big Sur 11.1
 - KeyboardShortcuts version: 0.7.0
 - Due to backward compatibility I use RecorderCocoa instead of Recorder

## Additional information
- Clicking `Record Shortcut` changes to `Press shortcut` as long as left mouse button is clicked and skips back to `Record shortcut` after mouse button release.
- When double clicking `Record Shortcut` field it changes to `Press shortcut`, but does not allow any combinations, only plain single letters. But the `x` button will appear again.

**Comment by sindresorhus** [comment]
I cannot reproduce with the example app. I tried adding this package to a new Cocoa project that uses Storyboards and using `RecorderCocoa` and I could still not reproduce it.

The only difference is that I'm on macOS 11.2. So maybe try upgrading macOS.

**Comment by adur1990** [comment]
Hi,

thank you for your reply.

I created a simple [app where this issue happens.](https://github.com/sindresorhus/KeyboardShortcuts/files/5995859/KeyboardShortcutBugExample.zip)

I also attached a screencast, where you can see the issue happen.
On the left side, you can see what keys I'm pressing.
In the right is the simple example app.
First, I delete the shortcut and immediately enter a new one, which works as intended.
After that, I delete the shortcut and click outside.
You can see afterwards that it is not possible to get the focus of the text field back until I double click.
But then, I want to use the same shortcut as before, but it is not registered correctly.
I have to delete the wrong shortcut and then I am able to record a new shortcut normally.
Hope this helps.


https://user-images.githubusercontent.com/10381899/108210032-55167680-712b-11eb-92e1-c8c0ccc49553.mov

**Comment by hank121314** [comment]
Hi @adur1990 !
Can confirm the issue.
At line 173 in RecorderCocoa.swift.
https://github.com/sindresorhus/KeyboardShortcuts/blob/f57a1e998d915d847e55da2c9f143d5adcf46639/Sources/KeyboardShortcuts/RecorderCocoa.swift#L173
Using `self.frame` to check whether `clickPoint` is in the inputField.
But in your simple project, `self.frame` is generated by its superview’s coordinate system(NSGridView).
So we might need to use `NSView.convert` to get the frame size by its own coordinate system.

I have already made a patch in [my fork](https://github.com/hank121314/KeyboardShortcuts).
Could you please help me to test whether the patch fixed your issue?

**Comment by adur1990** [comment]
Hi @hank121314,

I can confirm, that your fix is working. I tested it in the example app I posted above and in my actual app I am currently developing.

You should create a pull request to get this fix merged upstream.

Thank you for your help. Please let me know if I can do anything else.

**Comment by hank121314** [comment]
Hi @adur1990 ,

I have made some update in this patch.
Would you mind testing the patch again?
Thank you for your help! 😄 

If it works, I will create a pr.

**Comment by adur1990** [comment]
Hi,

I can confirm that your update still works in both, the example app from above and my app.

Thanks for tracking this issue down.
