### ISSUE TITLE
foregroundColor view modifier has no effect

### ISSUE THREAD

**Issue by jhoughjr** [sindresorhus/KeyboardShortcuts#42]
Im trying to set the color of the text for the shortcut but can find no way to do it.

**Comment by sindresorhus** [comment]
There's no support for that. Why are you trying to change the color? You should generally not change the color or style of built-in components (in this case it's just a stock text field).

**Comment by phaibin** [comment]
In case the shortcut conflicts with another, should turn the text to red, or something like that.
