### ISSUE TITLE
Keyboard Shortcuts with Special Function Keys

### ISSUE THREAD

**Issue by biocross** [sindresorhus/KeyboardShortcuts#47]
Hello, firstly thank your amazing work on this library, it's super useful!

I wanted to know if there's way to map keyboard shortcuts to the special function keys on the keyboard, like the increase /decrease **brightness**/**volume** keys (on the first row on Apple keyboards)

For now, when recording a shortcut, these keys are not recognised at all (or maybe macOS just hijacks them). If I try using **fn** button + these keys, it maps to **F1**/**F2** etc instead, which are not the same thing.

**Comment by sindresorhus** [comment]
As far as I know, that's not possible. They are intercepted by the system before they reach any keyboard shortcut listener.

**Comment by biocross** [comment]
Got it, thank you.  

I did find a package here https://github.com/nhurden/MediaKeyTap that worked, but it does require additional **accessibility permissions** from system preferences.
