### ISSUE TITLE
Help for multiple/variable `KeyboardShortcuts.Recorder(for: )`

### ISSUE THREAD

**Issue by Yang-Xijie** [sindresorhus/KeyboardShortcuts#52]
Hi, feel happy to meet such a easy-to-use package. 

However, I checked the Example and found if you need more shortcut kinds, it seems you have to set them fixed.

```swfit
extension KeyboardShortcuts.Name {
    static let testShortcut1 = Self("testShortcut1")
    static let testShortcut2 = Self("testShortcut2")
    static let testShortcut3 = Self("testShortcut3")
    static let testShortcut4 = Self("testShortcut4")
}
```

What if I want to use user-customizable/variable shortcut kinds? For example, like Manico in the App Store, it allows users to set shortcuts for each application. But the developer cannot know the required amount.

One obvious solution is to use `static let testShortcut1 = Self("testShortcut1")` 10 or 100 times. In that case it's always adequate for requirements. Is there any other way to achieve that?

Appreciate for any hints including tricks in Swift language!

**Comment by sindresorhus** [comment]
See: https://github.com/sindresorhus/KeyboardShortcuts#dynamic-keyboard-shortcuts

The example project shows this off too: https://github.com/sindresorhus/KeyboardShortcuts/blob/a7a3ff6248b7564ef4ef2e9003672bf1b9f77ad1/Example/KeyboardShortcutsExample/ContentView.swift#L41-L86
