### ISSUE TITLE
Get all shortcuts that user has set in KeyboardShortcuts

### ISSUE THREAD

**Issue by Yang-Xijie** [sindresorhus/KeyboardShortcuts#53]
I wonder if there is a way to print all KeyboardShortcuts.Name? Thanks for any hints!

**Comment by sindresorhus** [comment]
I think an API for this would be useful. I don't have the time to think about the name and write docs right now, but here's how you can achieve it:

```swift
extension KeyboardShortcuts {
	static var allSavedNames: [Name] {
		UserDefaults.standard
			.dictionaryRepresentation()
			.filter { $0.key.hasPrefix("KeyboardShortcuts_") }
			.compactMap { Name($0.key) }
	}
}
```
