### ISSUE TITLE
Allows recording shortcuts with shift, that trigger no action

### ISSUE THREAD

**Issue by henribredt** [sindresorhus/KeyboardShortcuts#54]
The recorder allows creating a new shortcut just with shift as the modifier, for example _Shift + X_, but executing this shortcut leads to no action. I've actually got an App Store rejection because of this issue, funny because many apps using this super useful library (thanks ;) ) are available on the App Store :)

**Comment by sindresorhus** [comment]
Thanks for reporting. I'm surprised I never encountered this bug either. I use this package in many popular apps.

https://github.com/sindresorhus/KeyboardShortcuts/releases/tag/v1.2.1
