### ISSUE TITLE
Shortcuts Using Media Keys

### ISSUE THREAD

**Issue by Muirium** [sindresorhus/KeyboardShortcuts#56]
Hi folks,

An issue I'm seeing with [MonitorControl](https://github.com/MonitorControl/MonitorControl/discussions/631) is apparently worth your attention, as it uses KeyboardShortcuts to assign its custom keyboard controls. Here's a screenshot:
![Screenshot 2021-10-05 at 1 26 31 pm](https://user-images.githubusercontent.com/221646/136022109-076e5682-62a7-47b7-a921-81f269dd4aae.jpg)
(MonitorControl allows controlling Brightness etc. on external displays, much like they were Apple ones, via a common display feature called DDC.)

I'd like to use the Increase Brightness and Decrease Brightness keys on my M1 Air's built in keyboard (and chord them with Shift for Contrast control). Unfortunately, they don't show up unless I turn them into F1 and F2 by holding Fn. Ideally, all such media keys should be available for making custom keyboard shortcuts.

Those media keys are available to [Karabiner](https://github.com/pqrs-org/Karabiner-Elements). They use extended key codes, which is why I was not surprised! Many apps can't "see" them. Which leaves them open for many user defined shortcuts!

My original report:
https://github.com/MonitorControl/MonitorControl/discussions/631#discussioncomment-1429723

**Comment by sindresorhus** [comment]
Media keys cannot be supported: https://github.com/sindresorhus/KeyboardShortcuts/commit/04fdf3380e21aff27cbbc82a7742cddc33a27d09
