### ISSUE TITLE
Cannot add as SPM

### ISSUE THREAD

**Issue by thedoubler** [sindresorhus/KeyboardShortcuts#58]
Cannot add this package as Swift Package Manager.

> Dependencies could not be resolved because root depends on 'KeyboardShortcuts' 1.3.0..<2.0.0.
> 'KeyboardShortcuts' >= 1.3.0 cannot be used because no versions of 'KeyboardShortcuts' match the requirement 1.3.1..<2.0.0 and 'KeyboardShortcuts' 1.3.0 contains incompatible tools version (5.5.0).

Environment: Version 12.5.1 
MacOS: 11.5.2

**Comment by sindresorhus** [comment]
As the error message points out, Swift 5.5 is required, which means you need to be on Xcode 13.
