### ISSUE TITLE
Package resolution failed ...

### ISSUE THREAD

**Issue by soundflix** [sindresorhus/KeyboardShortcuts#61]
"because KeyboardShortcuts >=1.2.0 contains incompatible tools version and root depends on KeyboardShortcuts 1.3.0..<2.0.0, version solving failed."

adding 1.1.0 to frameworks works.
Any idea what I'm doing wrong?

Xcode 12.4, macOs 10.15.7

**Comment by sindresorhus** [comment]
Duplicate of #58
