### ISSUE TITLE
save Keyboard Layout alongside KeyCode?

### ISSUE THREAD

**Issue by godbout** [sindresorhus/KeyboardShortcuts#62]
just some thoughts. i had the case in an app where i had to support different Keyboard Layouts. all good. for the Keyboard Shortcut, there's two possible ways:

1. not caring about the Keyboard Layout. like you saved `shift-command-a` on a US QWERTY, you have would have to press `shift-command-q` on a French AZERTY (Virtual Keyboard). same KeyCode, different character.
2. keep the Keyboard Layout alongside the KeyCode. you saved `shift-command-a` on a US QWERTY, you would have to press `shift-command-a` on a French AZERTY. same character, different KeyCode.

i'm not sure if any solution is better than the other. like a Keyboard Shortcut should be more of a position than of a key character per se. but at the same time with the current UI that does not care about the Keyboard Layout it's a little confusing.

it's easy to add this out of Keyboard Layout in our own project, but maybe an idea for KeyboardShortcuts? or maybe the idea makes no sense. that would work too.

**Comment by sindresorhus** [comment]
What's the use-case?

**Comment by godbout** [comment]
people switching Keyboard Layouts. (i personally don't. stick to US QWERTY.) if someone record their KeyboardShortcut on a QWERTY with `shift-command-a`, once you switch to AZERTY KeyboardShortcut will show `shift-command-a` in the Preferences while you need to press `shift-command-q`. so there is inconsistency. but honestly yeah, probably only a small number of people would bother. even what *is* the best solution is not clear. may depend on people's preferences. some may want the character, some may want the move. anyways. computers. probably better we close this and go to sleep. thanks.

**Comment by sindresorhus** [comment]
Yeah, I don't think it's worth the complexity.
