### ISSUE TITLE
Localizable doesn't work.

### ISSUE THREAD

**Issue by jacklandrin** [sindresorhus/KeyboardShortcuts#63]
I tried to add ".environment(\.locale, .init(identifier: "xxx"))" to support localizable in my SwiftUI project, but it only displays as English. I found the SwiftUI_Previews in your package, in the preview also like this. So, how to implement KeyboardShortcuts localizable in a SwiftUI project?

**Comment by sindresorhus** [comment]
That's not how you add localizations to a project. That's just how we force it in the preview. I would recommend reading the Apple docs on how to localize your project.

**Comment by jacklandrin** [comment]
Can I force to set a language for KeyboardShortcuts? Or its language just follows the system?

**Comment by sindresorhus** [comment]
It follows the app's language.
