### ISSUE TITLE
Use only modifiers and shortcut

### ISSUE THREAD

**Issue by DoidoYo** [sindresorhus/KeyboardShortcuts#65]
Hello, 

Love the library. Im trying to use only the option + command modifier keys and all function requires an associated non modifier key. anyway to get around this?

**Comment by sindresorhus** [comment]
I'm not sure that's possible, and even if it is, it's not something I want to support. No other keyboard shortcut recorder solution I'm aware of supports this either. I recommend using a shortcut with both a modifier and key.
