### ISSUE TITLE
How do I get the KeyboardShortcuts Example into a storyboard viewController Window?

### ISSUE THREAD

**Issue by pauljvallance** [sindresorhus/KeyboardShortcuts#68]
Does anyone knows how to get the SwiftUI View (MainScreen in the example) into a storyboard viewController ( or NSHostingController?) so that it can be called  with the following Shortcut functiion in App.delegate.

`
let menu = NSMenu()

menu.addItem(NSMenuItem(title: "Set Shortcut", action: #selector(AppDelegate.Shortcut(sender:)), keyEquivalent: "" ))
statusItem.menu = menu
}
    @objc func Shortcut(sender: NSMenuItem){

        //call the HostingViewController / SwiftUI View here

        }
`

Regards
Paul

**Comment by sindresorhus** [comment]
There's a Cocoa example here: https://github.com/sindresorhus/KeyboardShortcuts#cocoa

You don't need to use SwiftUI at all. How to get a `NSView` into a storyboard is expected knowledge and not something I intend to document here.

https://www.google.com/search?client=safari&rls=en&q=custom+view+storyboard&ie=UTF-8&oe=UTF-8&safari_group=9

**Comment by pauljvallance** [comment]
I didn't see your Cocoa example, I only found the SwiftUI example, hence my question!  I didn't expect you to document straightforward stuff.  Just thought you might respond nicely without the 'attitude'.
