### ISSUE TITLE
Shortcut default combination

### ISSUE THREAD

**Issue by leits** [sindresorhus/KeyboardShortcuts#7]
Is it possible to add a default keys combination for the shortcut?

**Comment by sindresorhus** [comment]
Not yet, but it makes sense to add support for that. I imagine it would be something like:

```swift
extension KeyboardShortcuts.Name {
	static let toggleUnicornMode = Name("toggleUnicornMode", default: Shortcut(.a, modifiers: [.command]))
}
```

However, I would recommend not predefining keyboard shortcuts unless it's absolutely necessary. Users find it annoying when random apps steal their existing keyboard shortcuts. It's generally better to show a welcome screen on the first app launch that lets the user set the shortcut.

**Comment by gpoitch** [comment]
Trying to migrate from an existing keyboard shortcut solution to this and would need something like this to register keys the user already has saved.

**Comment by gpoitch** [comment]
I can work on this if we iron out the API.  Proposal:
```swift
KeyboardShortcuts.Shortcut(name: "toggleUnicornMode", key: .a, modifiers: [.command], onKeyUp: {
  self.isUnicornMode.toggle()
})
```
The initializer will create the strongly-typed name for reference elsewhere instead of being a separate step.  key/modifier is optional for supporting defaults/hard-coded shortcuts.  And optionally setting onKeyUp/onKeyDown here instead of a separate step.

**Comment by sindresorhus** [comment]
@gpoitch Keyboard shortcut names are registered in `extension extension KeyboardShortcuts.Name` so they're available at any time. With `KeyboardShortcuts.Shortcut(name: "toggleUnicornMode"`, it could be possible for something to try to get the shortcut by name before the name has been registered. I also don't want multiple ways to do the same thing.

I have intentionally decoupled names from shortcuts, as a shortcut never changes, but a name can have its shortcut changed.

What are your concerns with doing the following?

```swift
extension KeyboardShortcuts.Name {
	static let toggleUnicornMode = Name("toggleUnicornMode", default: Shortcut(.a, modifiers: [.command]))
}
```

**Comment by gpoitch** [comment]
Ok, I can just do that.  Found the current api a bit scattered but I guess you have to set the names upfront.

PR: #13
