### ISSUE TITLE
v1.5.0 `AsyncStream` issue

### ISSUE THREAD

**Issue by bnidevs** [sindresorhus/KeyboardShortcuts#74]
I am getting a
```
Converting non-sendable function value to '@Sendable (AsyncStream<Void>.Continuation.Termination) -> Void' may introduce data races
```
error after importing v1.5.0

**Comment by bnidevs** [comment]
Clarifying:
Line 427 of https://github.com/sindresorhus/KeyboardShortcuts/blob/main/Sources/KeyboardShortcuts/KeyboardShortcuts.swift

**Comment by sindresorhus** [comment]
Are you on Xcode 13.3? If not, try that.

**Comment by bnidevs** [comment]
that fixed it, thanks
