### ISSUE TITLE
can't focus on KeyboardShortcuts Recorder input

### ISSUE THREAD

**Issue by godbout** [sindresorhus/KeyboardShortcuts#76]
```swift
...
@FocusState private var shouldRecordCustomShortcut: Bool
...
.onChange(of: enterNormalModeWith) { _ in
    shouldRecordCustomShortcut = true
}
...
KeyboardShortcuts.Recorder(for: .enterNormalMode).focused($shouldRecordCustomShortcut)
```

i would expect the `KeyboardShortcuts Recorder` to be focused and being able to type a shortcut to be recorded. but although the code removes the focus from any other field, the `KeyboardShortcuts Recorder` doesn't get focused.

if i replace the `KeyboardShortcuts Recorder` by any other field, it works. so my code itself seems to be fine.

any more info i could give to help? thanks.

**Comment by sindresorhus** [comment]
What are you trying to do? The recorder is not a normal text input even if it looks like it.

**Comment by godbout** [comment]
i'm trying to make the UX for the user as smooth as possible, like your libraries.

https://user-images.githubusercontent.com/121373/162681641-a82395a4-7f9d-4f81-8e5d-a02009a88eaf.mp4

when the user picks that he wants to use a custom shortcut and the field appears, i don't want them to have to click on the field. i wanted them to just have to press their shortcut to record it. having to click on the field first feels overwhelmingly dirty (no exaggeration of course).
