### ISSUE TITLE
Is there a way to detect if modifier keys still pressed on key up?

### ISSUE THREAD

**Issue by sarunw** [sindresorhus/KeyboardShortcuts#89]
Right now `KeyboardShortcuts.onKeyUp` recognize key up when users release non-modifier keys.

Is there a way to detect whether modifier keys are still pressed or not? 

I want to replicate the "command+tab" behavior where users can cycle through items while modifier keys still down.

**Comment by sarunw** [comment]
Thanks for the prompt response, but I don't understand the solution provided 😅

Let's say I want to replicate the functionality of `Command+Tab` with `Command+Control+Tab`.

After `Command+Control+Tab` is recognized, what should I check in the timer?

This is the function I try to replicate.
1. After `Command+Tab`, I want to show opened app.
2. While holding `Command`, you can release `Tab`.
3. Press `Tab` again would move the selection.
4. Release both `Command` and `Tab` will select and dismiss the window.

![CleanShot 2022-07-08 at 07 10 57](https://user-images.githubusercontent.com/795368/177891655-00b9a0c4-088b-454a-bde6-a161d33333d8.gif)

**Comment by sindresorhus** [comment]
You could maybe register Command+Tab as a global keyboard shortcut, and then have a [check](https://developer.apple.com/documentation/appkit/nsevent/1534971-addlocalmonitorforevents) for whether the Command key is still pressed, and hide the window if not.

Or you could check for `NSEvent.modifierFlags.contains(.command)` in keyUp.
